### ISSUE TITLE
Check possible bug in simba cron job archived audit logs

### ISSUE THREAD

**Issue by PhilipNollet** [cegeka/simba-os#7]
When the archived audit logs table is already filled and a re-deploy  happens, check that no errors occur

**Comment by BartCr** [comment]
When checking the auditlog for tampering, a new digest was calculated and compared against the stored digest using equals. The digests are being generated using a random salt, so they would hardly ever be equal.

**Comment by BartCr** [comment]
The fix now check to stored digest against the computed message using Jasypt provided methods.
